### ISSUE TITLE
Cannot Open An Image That is "In-Use"

### ISSUE THREAD

**Issue by paulhlee1967** [fadden/CiderPress2#16]
CiderPress 1 allows me to open up a disk image that is in use (for example in AppleWin) in a READ-ONLY mode. CiderPress2 fails to open the image at all with an error that the file is in use.

**Comment by fadden** [comment]
That is supposed to work, though you have to do it with the understanding that AppleWin is allowed to cache data in memory, and as a result the disk image file may not be consistent.

The .NET file sharing flags are supposed to allow you to open the file for read-only or read-write, and then control how the file is shared (i.e. how it can be opened by other processes).  If I open it read-write and share read-write, the other process can open it read-write.  If I open it read-only and share read-only, the other process can open it read-only.  If I open it read-write and share read-only, the other process can't open it at all.  So either I'm doing something wrong or .NET / Windows is misbehaving.  I'll need to dig into it more.

**Comment by fadden** [comment]
This appears to work correctly now.  I also updated the command-line tool, so it's possible to e.g. get a catalog from a disk image open in an emulator.  The info panel for the top-level entity has an added message.

**Comment by paulhlee1967** [comment]
Nice. TY. Is it published in any of the DEV releases ye?

**Comment by fadden** [comment]
It's now available as https://github.com/fadden/CiderPress2/releases/tag/v1.0.1-dev3

**Comment by fadden** [comment]
Available in v1.0.1.
